[versions]
agp = "8.6.1"
collection = "1.3.0"

[libraries]
collection = { module = "androidx.collection:collection", version.ref = "collection" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
