[versions]
agp = "8.13.0"
collection = "1.5.0"

[libraries]
collection = { module = "androidx.collection:collection", version.ref = "collection" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
